# Generated by Django 6.0.5 on 2026-06-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_item_delete_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://static.vecteezy.com/system/resources/previews/057/769/953/non_2x/a-cute-cartoon-illustration-of-a-smiling-golden-food-item-png.png', max_length=500),
        ),
    ]
