# Generated by Django 6.0.5 on 2026-07-02 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0008_alter_item_item_name_alter_item_item_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['user_name', 'item_price'], name='foodapp_ite_user_na_30c0f0_idx'),
        ),
    ]
